### ISSUE TITLE
Support for Python 3.13?

### ISSUE THREAD

**Issue by mwtoews** [conda-forge/pymetis-feedstock#17]
With Python 3.13 now out it would be appreciated to re-build PyMetis-2023.1.1 for Python 3.13

**Comment by inducer** [comment]
With the amount of work that maintainers get stuck with, a PR making this possible would be appreciated.

**Comment by mwtoews** [comment]
I'll look into it. This is normally done automatically, or done with `conda smithy rerender`, but something is preventing adding Python 3.13, so I'm trying to track this anomaly down...

**Comment by jakirkham** [comment]
Please check on [the package status in the migration]( https://conda-forge.org/status/migration/?name=python313 )

FWICT it is still waiting for parent packages to be migrated before this can be

Once it is ready the bot should make a PR

![Image](https://github.com/user-attachments/assets/b0087e8c-3c66-4800-ad47-cd2ab5feaa81)

**Comment by mwtoews** [comment]
Thanks @jakirkham ! I can chase some of these upstream to try and get them built...
